version: "2"
services:
  info:
    build: games_api/.
    ports:
      - "5000:5000"
    volumes:
      - ./games_api:/usr/src/app
    depends_on:
      - mongo

  reviews:
    build: reviews_api/.
    ports:
      - "8080:8080"
    volumes:
      - ./reviews_api:/usr/src/app

  mongo:
    image: mongo:3.4
    ports:
      - "27017:27017"
    volumes:
      - ./data/mongodb:/data/db